stages:
  - build
  - check

default:
  image: rust

build:
  stage: build
  script:
    - cargo build
  artifacts:
    paths:
      - target/
  only:
    - master

check:
  stage: check
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo fmt -- --check
    - cargo clippy --workspace --all-targets --
  only:
    - master