[package]
name = "github-rust-tool"
version = "0.0.1"
authors = ["Marvin Sextro <marvin.sextro@gmail.com>"]
edition = "2018"

[dependencies]
quicli = "0.4"
structopt = "0.3.17"
tokio = { version = "1.6.0", features = ["full"] }
futures = "0.3.15"
async-gitlib = "0.0.2"
